In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/content/laptopData.csv')

Delete all row which only contain NULL value

In [5]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [6]:
df[df.isnull().all(axis=1)]

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.dropna(how='all', inplace=True)

In [8]:
df.shape

(1273, 12)

In [9]:
df.head(3)

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000

Now we will check the each columns

In [10]:
df['Ram'].isna().sum()

np.int64(0)

In [11]:
df['Company'].isna().sum()

np.int64(0)

In [12]:
df['TypeName'].isna().sum()

np.int64(0)

In [13]:
df['Inches'].isna().sum()

np.int64(0)

In [14]:
df['ScreenResolution'].isna().sum()

np.int64(0)

In [15]:
df['Cpu'].isna().sum()

np.int64(0)

In [16]:
df['Ram'].isna().sum()

np.int64(0)

In [17]:
df['Memory'].isna().sum()

np.int64(0)

In [18]:
df['Gpu'].isna().sum()

np.int64(0)

In [19]:
df['OpSys'].isna().sum()

np.int64(0)

In [20]:
df['Weight'].isna().sum()

np.int64(0)

In [21]:
df['Price'].isna().sum()

np.int64(0)

**Ram Columns Description** `Categorical`

- Remove GB from the Ram columns so that i can convert this columns datatype into int.

In [22]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [23]:
df[~df['Ram'].str.endswith('GB', na=False)]

Empty DataFrame
Columns: [Unnamed: 0, Company, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price]
Index: []

In [24]:
#Remove the GB from the all Ram

df['Ram'] = df['Ram'].str[:-2]

In [25]:
df['Ram'] = df['Ram'].astype('int8')

In [26]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

**Weight columns** `Numerical`

- In this column 1 value is missing

In [27]:
df[~df['Weight'].str.endswith('kg')]

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
208,208.0,Dell,Ultrabook,13.3,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,8,256GB SSD,Intel UHD Graphics 620,Windows 10,?,77202.72

Fill the missing of weight with duplicate value which is avilable in this columns

In [28]:
df.loc[~df['Weight'].str.endswith('kg', na=False), 'Weight'] = '1.4kg'

In [29]:
df[~df['Weight'].str.endswith('kg')]

Empty DataFrame
Columns: [Unnamed: 0, Company, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price]
Index: []

**Remove the kg from the last of all values in this column so that i can convert this datatype of this into float**

In [30]:
df[~df['Weight'].str.endswith('kg', na=False)]

Empty DataFrame
Columns: [Unnamed: 0, Company, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price]
Index: []

In [31]:
df['Weight'] = df['Weight'].str[:-2]

In [32]:
df['Weight(In Kg)'] = df['Weight'].astype('float64')

In [33]:
df.drop(columns=['Weight'], inplace=True)

In [34]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,71378.6832,1.37
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,47895.5232,1.34
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,30636.0000,1.86
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,135195.3360,1.83
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,96095.8080,1.37

Remove the Unnamed: 0 column because this columns is not imp.

In [35]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [36]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,71378.6832,1.37
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,47895.5232,1.34
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,30636.0000,1.86
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,135195.3360,1.83
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,96095.8080,1.37

**Inches Columns** `Numerical`

- In this column 1 value is dirty

In [37]:
df[df['Inches'] == '?']

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
476,Dell,Workstation,?,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8,256GB SSD,Nvidia Quadro M1200,Windows 10,128298.24,1.78

In [38]:
df[(df['Company'] == 'Dell') & (df['TypeName'] == 'Workstation') & (df['Ram'] == 8) & (df['OpSys'] == 'Windows 10') & (df['ScreenResolution'] == 'Full HD 1920x1080')]

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
387,Dell,Workstation,15.6,Full HD 1920x1080,Intel Core i5 6440HQ 2.6GHz,8,500GB HDD,AMD FirePro W5130M,Windows 10,72940.32,2.23
447,Dell,Workstation,15.6,Full HD 1920x1080,Intel Xeon E3-1505M V6 3GHz,8,64GB Flash Storage + 1TB HDD,Nvidia Quadro M620,Windows 10,106187.04,2.23
476,Dell,Workstation,?,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8,256GB SSD,Nvidia Quadro M1200,Windows 10,128298.24,1.78
869,Dell,Workstation,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8,1TB HDD,Nvidia Quadro M620,Windows 10,94731.84,2.23

In [39]:
df['Inches'] = df['Inches'].str.replace('?', '15.6').astype('float64')

In [40]:
df[df['Inches'] == '?']

Empty DataFrame
Columns: [Company, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Price, Weight(In Kg)]
Index: []

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1273 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1273 non-null   object
 1   TypeName          1273 non-null   object
 2   Inches            1273 non-null   float64
 3   ScreenResolution  1273 non-null   object
 4   Cpu               1273 non-null   object
 5   Ram               1273 non-null   int8
 6   Memory            1273 non-null   object
 7   Gpu               1273 non-null   object
 8   OpSys             1273 non-null   object
 9   Price             1273 non-null   float64
 10  Weight(In Kg)     1273 non-null   float64
dtypes: float64(3), int8(1), object(7)
memory usage: 110.6+ KB

In [42]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,71378.6832,1.37
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,47895.5232,1.34
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,30636.0000,1.86
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,135195.3360,1.83
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,96095.8080,1.37

**Memory**

In [43]:
df['Memory'].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '128GB SSD +  1TB HDD', '256GB SSD +  256GB SSD',
       '64GB Flash Storage', '32GB Flash Storage', '256GB SSD +  1TB HDD',
       '256GB SSD +  2TB HDD', '32GB SSD', '2TB HDD', '64GB SSD',
       '1.0TB Hybrid', '512GB SSD +  1TB HDD', '1TB SSD',
       '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '180GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '?', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid', '1.0TB HDD',
       '512GB SSD +  1.0TB Hybrid', '256GB SSD +  1.0TB Hybrid'],
      dtype=object)

In [44]:
df[df['Memory'] == '?']

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
770,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,16,?,AMD Radeon R7 M445,Windows 10,62938.0656,2.3

In [45]:
df[(df['Company'] == 'Dell') & (df['TypeName'] == 'Notebook') & (df['Inches'] == 15.6) & (df['ScreenResolution'] == 'Full HD 1920x1080') & (df['Ram'] == 16)]

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
180,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16,256GB SSD + 2TB HDD,AMD Radeon 530,Linux,55890.7200,2.02
235,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,16,256GB SSD,AMD Radeon R7 M445,Linux,47898.7200,2.36
487,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16,512GB SSD,Nvidia GeForce GTX 1050,Windows 10,101178.7200,2.06
513,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16,256GB SSD + 2TB HDD,AMD Radeon 530,Windows 10,64961.1072,2.20
583,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7600U 2.8GHz,16,256GB SSD,Nvidia GeForce 930MX,Windows 10,81912.1392,1.93
657,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16,256GB SSD + 2TB HDD,AMD Radeon 530,Windows 10,60472.8000,2.20
714,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7300U 2.6GHz,16,512GB SSD,Intel HD Graphics 620,Windows 10,76012.4448,1.93
770,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,16,?,AMD Radeon R7 M445,Windows 10,62938.0656,2.30
1063,Dell,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,16,2TB HDD,AMD Radeon R7 M445,Windows 10,52746.6672,2.32

In [46]:
df['Memory'] = df['Memory'].str.replace('?', '256GB SSD + 2TB HDD')

In [47]:
df.loc[770, 'Memory'] = '256GB SSD + 2TB HDD'

Round off the price into nearest integer and convert the datatype to int

In [48]:
df['Price'] = df['Price'].round().astype('int32')

In [49]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,71379,1.37
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,47896,1.34
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,30636,1.86
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,135195,1.83
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,96096,1.37

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1273 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1273 non-null   object
 1   TypeName          1273 non-null   object
 2   Inches            1273 non-null   float64
 3   ScreenResolution  1273 non-null   object
 4   Cpu               1273 non-null   object
 5   Ram               1273 non-null   int8
 6   Memory            1273 non-null   object
 7   Gpu               1273 non-null   object
 8   OpSys             1273 non-null   object
 9   Price             1273 non-null   int32
 10  Weight(In Kg)     1273 non-null   float64
dtypes: float64(2), int32(1), int8(1), object(7)
memory usage: 138.0+ KB

## OpOS column



1.   Make a seprate columns for every type of OS like 'Windows 10' and 'Windows 7' -> 'WindowsOS', 'macOS' and 'Mac OS X' -> 'MacOS', 'Linux' -> 'LinuxOS', 'Chrome OS' and 'Andorid' -> 'Other' and 'No OS' -> 'No_OS'

2. All this new columns only contain 0 or 1. 0 mean device not belong to the OS and 1 mean device belong to the OS

3. Finally delete this columns

In [51]:
df['OpSys'].unique()

array(['macOS', 'No OS', 'Windows 10', 'Mac OS X', 'Linux',
       'Windows 10 S', 'Chrome OS', 'Windows 7', 'Android'], dtype=object)

In [52]:
df['OpSys'] = df['OpSys'].str.replace('Mac OS X', 'macOS')

In [53]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg)
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,71379,1.37
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,47896,1.34
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,30636,1.86
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,135195,1.83
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,96096,1.37

In [54]:
df['OpSys'].unique()

array(['macOS', 'No OS', 'Windows 10', 'Linux', 'Windows 10 S',
       'Chrome OS', 'Windows 7', 'Android'], dtype=object)

In [55]:
df['OpSys'] = df['OpSys'].str.replace('Windows 10 S', 'Windows 10')

In [56]:
df['Windows'] = df['OpSys'].str.startswith('Windows').astype('int')

In [57]:
df['Mac'] = df['OpSys'].str.startswith('macOS').astype('int')

In [58]:
df['Linux'] = (df['OpSys'] == 'Linux').astype('int')

In [59]:
df['OtherOS'] = ((df['OpSys'] == 'Chrome OS') | (df['OpSys'] == 'Android')).astype('int')

In [60]:
df.rename(columns={'Windows': 'WindowsOS'}, inplace=True)

In [61]:
df.rename(columns={'Mac': 'MacOS'}, inplace=True)

In [62]:
df.rename(columns={'Linux': 'LinuxOS'}, inplace=True)

In [63]:
df['No_OS'] = (df['OpSys'] == 'No OS').astype('int')

In [64]:
df.head(2)

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price,Weight(In Kg),WindowsOS,MacOS,LinuxOS,OtherOS,No_OS
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,71379,1.37,0,1,0,0,0
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,47896,1.34,0,1,0,0,0

In [65]:
df['OpSys'].unique()

array(['macOS', 'No OS', 'Windows 10', 'Linux', 'Chrome OS', 'Windows 7',
       'Android'], dtype=object)

In [66]:
df.drop(columns=['OpSys'], inplace=True)

In [67]:
df['MacOS'] = df['MacOS'].astype('int8')

In [68]:
df['WindowsOS'] = df['WindowsOS'].astype('int8')

In [69]:
df['LinuxOS'] = df['LinuxOS'].astype('int8')

In [70]:
df['OtherOS'] = df['OtherOS'].astype('int8')

In [71]:
df['No_OS'] = df['No_OS'].astype('int8')

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1273 entries, 0 to 1302
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1273 non-null   object
 1   TypeName          1273 non-null   object
 2   Inches            1273 non-null   float64
 3   ScreenResolution  1273 non-null   object
 4   Cpu               1273 non-null   object
 5   Ram               1273 non-null   int8
 6   Memory            1273 non-null   object
 7   Gpu               1273 non-null   object
 8   Price             1273 non-null   int32
 9   Weight(In Kg)     1273 non-null   float64
 10  WindowsOS         1273 non-null   int8
 11  MacOS             1273 non-null   int8
 12  LinuxOS           1273 non-null   int8
 13  OtherOS           1273 non-null   int8
 14  No_OS             1273 non-null   int8
dtypes: float64(2), int32(1), int8(6), object(6)
memory usage: 134.2+ KB

In [73]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,Price,Weight(In Kg),WindowsOS,MacOS,LinuxOS,OtherOS,No_OS
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,71379,1.37,0,1,0,0,0
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,47896,1.34,0,1,0,0,0
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,30636,1.86,0,0,0,0,1
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,135195,1.83,0,1,0,0,0
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,96096,1.37,0,1,0,0,0

## GPU Columns

- In this columns we seprate the Gpu brand and Gpu name in two columns
- and delete GPU col.

In [74]:
df['Gpu']

0       Intel Iris Plus Graphics 640
1             Intel HD Graphics 6000
2              Intel HD Graphics 620
3                 AMD Radeon Pro 455
4       Intel Iris Plus Graphics 650
                    ...
1298           Intel HD Graphics 520
1299           Intel HD Graphics 520
1300               Intel HD Graphics
1301              AMD Radeon R5 M330
1302               Intel HD Graphics
Name: Gpu, Length: 1273, dtype: object

In [87]:
df['Gpu_brand'] = df['Gpu'].str.split(' ').str[0]

In [96]:
df.insert(8, 'Gpu_brand', df.pop('Gpu_brand'))

In [94]:
df['Gpu_name'] = df['Gpu'].str.replace(r'Intel|AMD|Nvidia|ARM', '', regex=True).str.strip()

In [97]:
df.insert(9, 'Gpu_name', df.pop('Gpu_name'))

In [98]:
df.head(2)

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,Gpu_brand,Gpu_name,Price,Weight(In Kg),WindowsOS,MacOS,LinuxOS,OtherOS,No_OS
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,Intel,Iris Plus Graphics 640,71379,1.37,0,1,0,0,0
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,Intel,HD Graphics 6000,47896,1.34,0,1,0,0,0

In [99]:
df.drop(columns=['Gpu'], inplace=True)

## Cpu Columns

In [106]:
df['Cpu_brand'] = df['Cpu'].str.split(' ').str[0]

In [108]:
df.insert(5, 'Cpu_brand', df.pop('Cpu_brand'))

In [141]:
df.head(2)

,Company,TypeName,Inches,ScreenResolution,Cpu,Cpu_brand,Cpu_name,Cpu_speed,Ram,Memory,Gpu_brand,Gpu_name,Price,Weight(In Kg),WindowsOS,MacOS,LinuxOS,OtherOS,No_OS
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Core i5 2.3GHz,Intel,Core i5,2.3GHz,8,128GB SSD,Intel,Iris Plus Graphics 640,71379,1.37,0,1,0,0,0
1,Apple,Ultrabook,13.3,1440x900,Core i5 1.8GHz,Intel,Core i5,1.8GHz,8,128GB Flash Storage,Intel,HD Graphics 6000,47896,1.34,0,1,0,0,0

In [110]:
df['Cpu_brand'].unique()

array(['Intel', 'AMD', 'Samsung'], dtype=object)

In [115]:
df['Cpu'] = df['Cpu'].str.replace(r'Intel|AMD|Samsung', '', regex=True).str.strip()

In [139]:
df['Cpu_speed'] = df['Cpu'].str.split(' ').str[-1]

In [140]:
df.insert(7, 'Cpu_speed', df.pop('Cpu_speed'))

In [145]:
df['Cpu_name'] = df['Cpu'].apply(lambda x: " ".join(x.split(' ')[:-1]))

In [151]:
df.insert(6, 'Cpu_name', df.pop('Cpu_temp'))

In [156]:
df.drop(columns=['Cpu'], inplace=True)

In [157]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu_brand,Cpu_name,Cpu_speed,Ram,Memory,Gpu_brand,Gpu_name,Price,Weight(In Kg),WindowsOS,MacOS,LinuxOS,OtherOS,No_OS
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3GHz,8,128GB SSD,Intel,Iris Plus Graphics 640,71379,1.37,0,1,0,0,0
1,Apple,Ultrabook,13.3,1440x900,Intel,Core i5,1.8GHz,8,128GB Flash Storage,Intel,HD Graphics 6000,47896,1.34,0,1,0,0,0
2,HP,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5GHz,8,256GB SSD,Intel,HD Graphics 620,30636,1.86,0,0,0,0,1
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7GHz,16,512GB SSD,AMD,Radeon Pro 455,135195,1.83,0,1,0,0,0
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1GHz,8,256GB SSD,Intel,Iris Plus Graphics 650,96096,1.37,0,1,0,0,0